# List All Collection

In [35]:
import chromadb
import numpy as np
from chromadb.config import Settings

embedding_dummy = np.random.randn(1024).tolist()

chromadb_setting = Settings(
    chroma_client_auth_provider="chromadb.auth.basic_authn.BasicAuthClientProvider",
    chroma_client_auth_credentials="userdata:userdataChromaPassw0rd",
)

client1 = chromadb.HttpClient(
    host="52.187.106.203",
    port=8000,
    settings=chromadb_setting,
)

client1.count_collections()

175

In [37]:
for collection in client1.list_collections():
    print(collection.get_model())

{'id': '008b34eb-e860-4a96-9f3b-65cfb0bc877f', 'name': 'misc.metadata.mvp2.kpiTableDescription', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '013ce7c8-13e3-4f02-af76-1d2196740070', 'name': 'testSher.ADA.banking.tableLevel', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 768, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '023ed2b0-2d2c-4c71-a57b-dbc16297a0a6', 'name': 'test.yamuna.mvp2Test6.tableLevel', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '034a2ee6-6f65-43cb-b5bd-8e68a738e378', 'name': 'test.yamuna.mvp2Test2.samples', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '0447f0a1-6839-48ce-b767-6b77c902edb6', 'name': 'misc.metadata.mvp2Test.samples', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '045b5c01-22c9-4334-90c7-40eb80e67aec', 'name': 'misc.yamuna.mvp2.vector_original_column', 'metadata': None, 'dimension': 1, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '0571e0c7-75e5-4329-bb42-b7b25b4b2fbc', 'name': 'test.embeddingmodels.NV_Embed_v2', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 4096, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '069743a7-af43-4efd-aabb-60b9d3f556b0', 'name': 'test.saraswatibrahmaputra.mvp2Test1.tableLevel', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '08f50b48-9d57-4d11-ad50-4ca87aba0048', 'name': 'testing_kim2', 'metadata': None, 'dimension': None, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '09245b91-1fbf-459d-96a9-ad4d03c15380', 'name': 'test.businessAgent.mvp2Test2.columnLevel', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '0da21c13-9a17-4981-a025-317127e72096', 'name': 'misc.metadata.mvp2Test4.tableLevel', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': None, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '0e5b7bab-131f-4c1b-8dee-5fb8b2a876e3', 'name': 'misc.yamuna.mvp2.vector_original_column_4', 'metadata': None, 'dimension': 1, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '0ec9bde0-ee5d-4f44-a753-1ca770501c1b', 'name': 'misc.metadata.mvp2TestNiyaz.samples', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '11a92795-a07b-4fad-b4f5-8011c4ccf6b0', 'name': 'test.yamuna.mvp2Test2.tableLevel', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '1779f59b-9d04-452b-bc02-88b627e5e730', 'name': 'test.ADA.demorashdan.samples', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '19a48628-30ef-466e-922f-54359dd0e569', 'name': 'test.saraswatibrahmaputra.mvp2Test3.columnLevel', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '1a23fffc-216f-482e-a4e1-56c45d5067ef', 'name': 'test.saraswatibrahmaputra.mvp2Test2.samples', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '1acd70e1-b226-430f-acd5-2a57eeab1d48', 'name': 'misc.metadata.mvp2Test1.columnLevel', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '1c4609c2-8b94-414a-a129-4fb51ac46e08', 'name': 'test.yamuna.mvp2Test1.tableLevel', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '1d1c0d45-fbce-49f0-83e2-d654efea1786', 'name': 'test.businessAgent.mvp2Test1.samples', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '1d7bde5c-bdeb-4efd-80d5-3f1fbdbbf788', 'name': 'liberty2.ADA.banking.tableLevel', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 768, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '1e30e488-77c6-411c-b34f-c604e7b2c6dc', 'name': 'test.saraswatibrahmaputra.mvp2Test2.columnLevel', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '1e95a034-f1ab-4ebf-8ceb-4248b2bc81ef', 'name': 'test.saraswatibrahmaputra.mvp2.samples', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '235b89fe-d471-41b3-abad-e5234a5af1ba', 'name': 'test.yamuna.mvp2Test1.resultLevel', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': None, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '242c298a-b7b3-46fc-8fbf-ea766f58b39f', 'name': 'test.embeddingmodels.NV-Embed-v2', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': None, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '26625234-7778-452a-a02d-075b36eb7264', 'name': 'misc.yamuna.mvp2.vector_original_column_kim', 'metadata': None, 'dimension': 1, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '28a58415-362e-45a0-ad57-d785336805be', 'name': 'test.brahmaputra.mvp2Test2.tableLevel', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '291a4060-453e-4196-b34b-d5f98940c92a', 'name': 'test.yamuna.mvp2Test1.samples', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '2a124929-3f03-4095-8f8e-40f57f2a66bc', 'name': 'misc.metadata.mvp2Test2.columnLevel', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '2cc22d24-8bda-4ab9-8931-a2bc21ebbf83', 'name': 'misc.yamuna.mvp2.vector_column_description_3', 'metadata': None, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '2cc73f51-864a-40d0-b832-cf4c7d33d4b8', 'name': 'demo.ADA.banking.tableLevel', 'metadata': None, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '2d3bd249-4b55-4d6c-af45-48422e87b61f', 'name': 'test.saraswatibrahmaputra.mvp2Test.columnLevel', 'metadata': None, 'dimension': None, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '2e01b965-68c2-4606-aa18-5334bccbce1c', 'name': 'test.embeddingmodels.Lajavaness', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '2e2b9ec1-03eb-4f05-ba10-514e6a6b7d99', 'name': 'devtest3.ADA.banking.columnLevel', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 768, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '2efa8bbd-22e7-4823-871f-46fe4b8f513e', 'name': 'test.embeddingmodels.GTE_Large_v1_5', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '2fa146de-00e4-4bd6-875a-2ed967e85ed4', 'name': 'test.yamuna.mvp2Test7.tableLevel', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '32e52e1c-f7aa-4b55-8a27-0f8bb135bede', 'name': 'test.yamuna.mvp2Test5.tableLevel', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '33de0a22-42e8-4cfe-bac0-875ab70888ff', 'name': 'misc.metadata.mvp2Test1.tableLevel', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '34716378-9709-4988-a207-a2e4b4db0683', 'name': 'my_new_collection', 'metadata': None, 'dimension': None, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '36d18ab5-6334-4eba-8ee7-30a660d72dfc', 'name': 'test.businessAgent.mvp2Test2.samples', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '38004b67-15e8-4bdd-80eb-05d45805434c', 'name': 'test.ADA.banking.tableLevel', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '382a246a-01d9-4fb2-a4cb-275afdbc1d13', 'name': 'test.yamuna.mvp2Test3.columnLevel', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '399dc347-b999-431e-a85f-851c2fdb4294', 'name': 'liberty.ADA.banking.tableLevel', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 768, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '39ebb9d3-8c64-4944-b8d2-cbfcd3d92fad', 'name': 'misc.metadata.mvp2TestNiyaz.columnLevel', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '3a791439-964d-494d-9a58-697fa54795b4', 'name': 'misc.yamuna.mvp2.vector_original_column_5', 'metadata': None, 'dimension': 1, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '3b1c0f58-b552-4809-aa2b-db4190f848d5', 'name': 'devtest.ADA.banking.samples', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '3ce352f7-2a88-4311-bbb7-00af35473013', 'name': 'test.saraswati.mvp2.tableLevel', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '3d9aeec2-cd31-49f2-a1cb-1abca2ed2888', 'name': 'misc.yamuna.mvp2.vector_samples', 'metadata': None, 'dimension': 1, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '426250d9-2d93-4e2c-8694-a02e5b83db7e', 'name': 'test.metadata.embeddings.columnLevel', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 768, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '443e34a4-527f-41f7-b592-dbf6d78b031a', 'name': 'misc.metadata.mvp2Test2.kpiTableDescription', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '4452e80e-a194-49db-b665-55925361ad4a', 'name': 'test.brahmaputra.mvp2.tableLevel', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '45521e48-c838-47d5-8058-8953a0b6f156', 'name': 'devtest3.ADA.banking.samples', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 768, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '473f5d87-128c-4216-9572-171e6c8380b8', 'name': 'test.metadata.embeddings_samples', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 768, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '47ac6c37-e564-4cee-9531-154bee265b13', 'name': 'test.businessAgent.mvp2Test1.tableLevel', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '47ac9991-b4c8-4f4a-b280-3c0b53fbd0c3', 'name': 'test.ADA.demo.samples', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '49d7ae3f-7537-40e7-8c51-575af5bb5e2c', 'name': 'test.ADA.bankingdemo.tableLevel', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '4b58d0c0-828b-4ce7-87ad-afb7f5385bb5', 'name': 'misc.yamuna.mvp2.vector_column_description_4', 'metadata': None, 'dimension': 1, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '4d1d17c7-4d00-43b3-9489-105f9f7b9a2f', 'name': 'testSher.ADA.bankingdemo.columnLevel', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '4dfc6e09-a0bb-481d-a615-842e9cbab9ff', 'name': 'test.yamuna.mvp2Test6.samples', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '4e2d13a0-2a8f-481f-804b-20f99b617de3', 'name': 'misc.ADA.bankingdemo.aiman.tableLevel', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '51451fd6-83ed-4117-8870-5f1d9ed98d5b', 'name': 'misc.yamuna.mvp2.vector_column_description_kim', 'metadata': None, 'dimension': 1, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '53f34c55-c925-401b-943b-dd831873431f', 'name': 'misc.metadata.mvp2.test', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 768, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '54a90204-1770-48f2-8352-98cf3f64d0bf', 'name': 'test.yamuna.mvp2Test4.samples', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '54eb7fce-5f7b-42ac-ae3a-3c74ff8f2b77', 'name': 'misc.ADA.metadata.AimanColumnLevel.samples', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '57f20ba4-462c-44b8-84c0-bbafa97e5ed6', 'name': 'test.metadata.embeddings.kpiTableDescription', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 768, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '5b8296f6-9c67-4e8c-b5bd-590d6f98f57a', 'name': 'my_new_collection6', 'metadata': None, 'dimension': None, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '62060305-1f4e-4f04-8c73-62b4843309c0', 'name': 'test.yamuna.mvp2Test2.columnLevel', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '6304a076-0ade-4317-8059-d66ea5dfa539', 'name': 'misc.ADA.moudy.tableLevel', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '67ae3e25-929f-4a69-8346-1f28146ff191', 'name': 'test.businessAgent.mvp2Test1.columnLevel', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '68da3e25-5334-4fd1-ad2f-e72c87c7fd16', 'name': 'misc.yamuna.mvp2.vector_column_description', 'metadata': None, 'dimension': 1, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '698d0529-b24d-44ea-bd32-45f9186df44e', 'name': 'test.saraswatibrahmaputra.mvp2.tableLevel', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '6b2cb518-9378-4075-b89c-f58cf45235f3', 'name': 'demo.ADA.banking.samples', 'metadata': None, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '6b6045fc-25f5-4790-8d98-622686c0e5e6', 'name': 'misc.ADA.metadata.AimanColumnLevel', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '6b8bfed4-67ca-4499-a7d8-29548836ce41', 'name': 'liberty.ADA.banking.tableLevel_kim', 'metadata': None, 'dimension': 768, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '6d102120-6c7f-40b9-95ef-4c075bac1f57', 'name': 'misc.metadata.mvp2Test4.columnLevel', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '6d1c8719-3a3b-48c4-b6b4-8981cbc48bf6', 'name': 'devtest2.ADA.banking.columnLevel', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '707b5486-ffb5-48e2-9a54-ec0f35a22fed', 'name': 'misc.ADA.bankingdemo.aiman.columnLevel', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '72023440-026d-4e27-967e-bffe6f0c44be', 'name': 'test.saraswati.mvp2.columnLevel', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '7293b37f-e4fb-4ef7-b403-47b188981cac', 'name': 'test.saraswatibrahmaputra.mvp2Test1.columnLevel', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '7306eb59-ebe5-47d8-9346-17392d0b28a8', 'name': 'test.BlueRiver.mvp2Test1.tableLevel', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': None, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '75b3137f-74d7-456f-aae8-a8d972856c63', 'name': 'test.brahmaputra.mvp2.columnLevel', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '782315b2-2de5-444b-bbcd-b5b0f089f251', 'name': 'test.yamuna.mvp2Test4.tableLevel', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '787de507-91cb-4fe1-ae94-266e5138c17b', 'name': 'test.saraswatibrahmaputra.mvp2Test3.tableLevel', 'metadata': None, 'dimension': None, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '78f83482-8c76-4a73-b98c-83e2c15a2100', 'name': 'test_collection', 'metadata': None, 'dimension': None, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '798afd12-ee90-496f-b766-3a45ed9f6528', 'name': 'test.brahmaputra.mvp2Test2.columnLevel', 'metadata': None, 'dimension': None, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '82d50682-b432-469f-b5c3-1d41593790dc', 'name': 'test.ADA.bankingdemo.columnLevel', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '830a001e-3af5-44b4-a0c0-498b65493d2a', 'name': 'test.ADA.bankingdemo.samples', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '83cf8c8b-1b02-431b-ae96-8ea0d4ad9e42', 'name': 'test.saraswati.mvp2.samples', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '83db25ee-2cb6-44e6-b6f2-43136da6ee93', 'name': 'test.yamuna.mvp2Test7.samples', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '85c08b97-561f-4ef9-8779-38cc255c7b5e', 'name': 'test.embeddingmodels.Stella_1.5B', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 1024, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}
{'id': '8894651c-082f-4b59-bf4e-7b34c2ba8344', 'name': 'devtest3.ADA.banking.tableLevel', 'metadata': {'hnsw:space': 'cosine'}, 'dimension': 768, 'tenant': 'default_tenant', 'database': 'default_database', 'version': 0}

# Check Table Level Metadata

In [1]:
import chromadb
import numpy as np
from chromadb.config import Settings

embedding_dummy = np.random.randn(1024).tolist()

chromadb_setting = Settings(
    chroma_client_auth_provider="chromadb.auth.basic_authn.BasicAuthClientProvider",
    chroma_client_auth_credentials="userdata:userdataChromaPassw0rd",
)

client2 = chromadb.HttpClient(
    host="52.187.106.203",
    port=8000,
    settings=chromadb_setting,
)

collection_name = "devtest4.ADA.banking.tableLevel"  # dev.ada-app.ai
# collection_name = "demo.ADA.banking.tableLevel" # test.ada-app.ai

tbl_collection = client2.get_collection(collection_name)

print(f"Collection: {collection_name}")
print(f"Number of Vectors: {tbl_collection.count()}")

tbl_collection.get(
    # embedding_dummy,
    # limit=tbl_collection.count(),
    # include=["metadatas", "documents", "embeddings"]
    # where={
    #     "database_name": "starhub_data_asset"
    # }
)["metadatas"]

Collection: devtest4.ADA.banking.tableLevel
Number of Vectors: 18

[{'column_list': 'age|age_group|cid|city|disability_status|education|education_level|employment_status|gender|has_credit_card|has_current_account|has_debit_card|has_loan|id|income_level|income_range|marital_status|nationality|no_dependents|occupation|occupation_industry|phone_number|postcode|race|religion|rfm_month|rfm_score_actual|rfm_score_projected|rfm_segment_actual|rfm_segment_projected|state',
  'database_identifier': 'label1',
  'database_name': 'ada_banks_data_asset',
  'foreign_key': 'N/A',
  'kpi_formula': '',
  'kpi_name': '',
  'last_metadata_update': '2024-10-19 01:02:13',
  'number_of_columns': '31',
  'primary_key': "['id']",
  'row_description': ' The row represents a 45-year-old female resident of Bintulu, Malaysia, who is a private employee with a diploma and undergraduate education, married, and has 2 dependents. She has a high income, owns a credit card, debit card, and has a loan. She works in the real estate industry as a property manager and is an active regular buyer, currently in the Engaged Premium Customer segment.',
  'source': 'N/A',
  'sql_database_name': 'MySQL',
  'table_description': " Table rfm_projection_new provides a predicted RFM (Recency, Frequency, Monetary value) score for each customer for the next quarter. The table includes demographic information such as age, gender, education, employment status, income level, and occupation industry. Customer identifiers like customer ID, phone number, and postcode are also present. The table's significant columns include rfm_score_actual and rfm_score_projected, which highlight the customer's current and predicted RFM scores. Additionally, rfm_segment_actual and rfm_segment_projected offer a categorized view of the customer's current and future RFM segments. This table plays a crucial role in forecasting customer behavior and aids in targeted marketing and customer relationship management strategies.",
  'table_description_v2': ' The "rfm_projection_new" table provides a high-level view of predicted customer behavior for the upcoming quarter. It serves to estimate each customer\'s Recency, Frequency, and Monetary value (RFM) scores, enabling proactive segmentation and targeted marketing strategies. By anticipating customer behavior, this table empowers data-driven decision-making to optimize customer engagement and business growth.',
  'table_name': 'rfm_projection_new',
  'table_short_description': 'Table "rfm_projection_new" predicts RFM scores for customers, essential for forecasting behavior and aiding targeted marketing strategies.',
  'table_type': 'DIMENSION'},
 {'column_list': 'actual_product_count|age|age_group|CID|city|cross_sell_product|Debit_Card_Junior|Debit_Card_Master|Debit_Card_Micro|Debit_Card_Visa|disability_status|education|education_level|Education_Loan|employment_status|gender|Hire_Purchase|Home_Loan|id|income_level|income_range|marital_status|Master_Card_Classic|Master_Card_Gold|Master_Card_Platinum|Master_Card_Priority|Micro_Loan|month|nationality|no_dependents|occupation|occupation_industry|Personal_Loan|phone_number|postcode|projected_product_count|race|religion|Share_Margin_Financing|state|year',
  'database_identifier': 'label1',
  'database_name': 'ada_banks_data_asset',
  'foreign_key': 'N/A',
  'kpi_formula': "Count of 'actual_product_count' that is greater than 1, Count of 'projected_product_count' that is greater than 1 with given distinct CID from the table filter by year1 and year2, grouped by year|Count of 'actual_product_count' that is greater than 1, Count of projected_product_count that is greater than 1 with given distinct CID from the table filter by year n grouped by month|Count of actual_product_count that is greater than 1, Count of projected_product_count that is greater than 1 with given distinct CID from the table filter by year n, grouped by each month between ‘y’ and ‘y1’ in year ‘n’|Count of actual_product_count that is greater than 1, Count of projected_product_count that is greater than 1 with given distinct CID from the table filter by year n and customers who hold any debit or master card, grouped by month|Count of actual_product_count that is greater than 1, Count of projected_product_count that is greater than 1 with given distinct CID from the table filter by year n and customerswho hold any type of loan (Home Loan, Personal Loan, Hire Purchase, etc.), grouped by month|Count of actual_product_count that is greater than 1, Count of projected_product_count that is greater than 1 with given distinct CID from the table filter by year n and month between ‘y’ and ‘y1’  and customers who hold any debit or master card, grouped by month|Count of actual_product_count that is greater than 1, Count of projected_product_count that is greater than 1 with given distinct CID from the table filter by year n and month between ‘y’ and ‘y1’  and customers who hold any type of loan (Home Loan, Personal Loan, Hire Purchase, etc.), grouped by month|average of ‘actual_product_count’ and average of ‘projected_product_count’, for each month in year ‘n’, grouped by month.|average of ‘actual_product_count’ and average of ‘projected_product_count’, for each month between ‘y1’ and ‘y2’ in year ‘n’, grouped by month.|average of ‘actual_product_count’ and average of ‘projected_product_count’,  for each year between ‘year1’ and ‘year2’,  grouped by year",
  'kpi_name': 'Projected customer with multiple product from year1 to year2|Projected customer with multiple product for year n|Projected customer with multiple product for year n, from month y to y1|projected customer with multiple CASA product for year n|projected customer with multiple loan product for year n|projected customer with multiple CASA product for year n, from month y to month y1|projected customer with multiple loan product for year n, from month y to month y1|projected average product holding count for year n|projected average product holding count for year n, from month y to month y1|projected average product holding count from year n to n1',
  'last_metadata_update': '2024-10-19 01:02:13',
  'number_of_columns': '41',
  'primary_key': "['id']",
  'row_description': ' The row represents a 41-year-old female individual from Bentong, Malaysia, with a degree in undergraduate education, employed in the agriculture industry, earning between RM 10,000 - RM 29,999, and living as a single person with no dependents. She holds a Debit Card - Junior and has a projected product count of 1.',
  'source': 'N/A',
  'sql_database_name': 'MySQL',
  'table_description': ' The "projection_customer_product_holding_timeline_new" table outlines the historical product holdings and projects future product acquisition of customers, contributing to key performance metrics (kpm) within the system. It includes columns for actual and projected product counts, customer demographics such as age, gender, education, income level, occupation, and marital status, as well as product categories like Debit Cards, Hire Purchase, Home Loans, and Share Margin Financing. The table also captures customer-specific data, such as CID, phone number, postcode, and state, enabling tailored customer interaction and product offering strategies. Additionally, it includes time-related columns like age group, month, and year to facilitate trend analysis (ta) and forecasting.',
  'table_description_v2': ' The projection_customer_product_holding_timeline_new table provides a comprehensive view of customer-product interactions over time within the system. It serves to track and project customer holdings, facilitating data-driven decision-making and strategic planning. By recording changes in customer-product relationships, this table offers valuable insights into customer behavior and product performance.',
  'table_name': 'projection_customer_product_holding_timeline_new',
  'table_short_description': 'The "projection_customer_product_holding_timeline_new" table outlines historical and projected product holdings, contributing to key performance metrics. It includes customer demographics, product categories, and customer-specific data for tailored strategies and trend analysis.',
  'table_type': 'DIMENSION'},
 {'column_list': 'customer_id|gender|income_range|loan_principal_amt|loan_sub_category|marital_status|month|product_type|projected_loan_principal_amt|projected_saving_current_balance|projected_total_cross_sales_value|religion|saving_current_balance|state|total_cross_sales_value|year',
  'database_identifier': 'label1',
  'database_name': 'ada_banks_data_asset',
  'foreign_key': 'N/A',
  'kpi_formula': 'SUM of total_cross_sales_value / Num of months and SUM of projected_total_cross_sales_value / Num of months',
  'kpi_name': 'CASA Product Penetration Value based on net average position (For n months)',
  'last_metadata_update': '2024-10-19 01:02:13',
  'number_of_columns': '16',
  'primary_key': 'N/A',
  'row_description': " The row represents a male customer, married with an income range of RM 10,000 - RM 29,999, who has taken out a RM 10,000 education loan in Selangor in 2023. The customer's current saving balance is RM 20,284,534.21, with a projected total cross-sales value of RM 20,284,534.21 and a projected loan principal amount of RM 20,284,534.21. The customer is Muslim and the row shows no change in the current balance.",
  'source': 'N/A',
  'sql_database_name': 'MySQL',
  'table_description': ' The "casa_penetration_value_projection_v2" table is a vital component of the system, providing detailed projections for Customer Accounts, Savings, and Loans (CASA). It tracks customer information, including demographics such as gender, income range, marital status, religion, and location (state). The table also details loan information, including principal amount, loan sub-category, and projected loan principal amount. Furthermore, it projects the saving current balance, total cross-sales value, and projected total cross-sales value. This table is essential for analyzing and predicting customer behavior and optimizing CASA performance metrics.',
  'table_description_v2': " The casa_penetration_value_projection_v2 table serves as a data repository for projected values related to cable network penetration. It is instrumental in forecasting and understanding market trends, enabling informed decision-making for strategic growth and resource allocation within the cable service sector. This versioned table also highlights the evolution of data models and projections over time, fostering continuous improvement in the organization's analytical capabilities.",
  'table_name': 'casa_penetration_value_projection_v2',
  'table_short_description': 'The "casa_penetration_value_projection_v2" table is a vital system component that projects CASA performance metrics and customer behavior, tracking demographics, loans, and savings.',
  'table_type': 'DIMENSION'},
 {'column_list': 'age|cid|credit_limit|cumulative_current_education_loan_cross_selling|cumulative_current_education_loan_penetration|cumulative_current_hire_purchase_cross_selling|cumulative_current_hire_purchase_penetration|cumulative_current_home_loan_cross_selling|cumulative_current_home_loan_penetration|cumulative_current_micro_loan_cross_selling|cumulative_current_micro_loan_penetration|cumulative_current_personal_loan_cross_selling|cumulative_current_personal_loan_penetration|cumulative_current_share_margin_financing_cross_selling|cumulative_current_share_margin_financing_penetration|cumulative_projected_education_loan_cross_selling|cumulative_projected_education_loan_penetration|cumulative_projected_hire_purchase_cross_selling|cumulative_projected_hire_purchase_penetration|cumulative_projected_home_loan_cross_selling|cumulative_projected_home_loan_penetration|cumulative_projected_micro_loan_cross_selling|cumulative_projected_micro_loan_penetration|cumulative_projected_personal_loan_cross_selling|cumulative_projected_personal_loan_penetration|cumulative_projected_share_margin_financing_cross_selling|cumulative_projected_share_margin_financing_penetration|current_education_loan_cross_selling|current_hire_purchase_cross_selling|current_home_loan_cross_selling|current_micro_loan_cross_selling|current_personal_loan_cross_selling|current_share_margin_financing_cross_selling|gender|has_education_loan|has_hire_purchase|has_home_loan|has_loan|has_micro_loan|has_personal_loan|has_share_margin_financing|l_freldt_dt|l_orgamt|l_plafon_efektif|month|nationality|occupation|projected_credit_limit|projected_education_loan_cross_selling|projected_hire_purchase_cross_selling|projected_home_loan_cross_selling|projected_micro_loan_cross_selling|projected_personal_loan_cross_selling|projected_share_margin_financing_cross_selling|race|religion|state|year',
  'database_identifier': 'label1',
  'database_name': 'ada_banks_data_asset',
  'foreign_key': 'N/A',
  'kpi_formula': "Total of 'projected_education_loan_cross_selling'|Total of 'projected_hire_purchase_cross_selling'|Total of 'projected_home_loan_cross_selling'|Total of 'projected_personal_loan_cross_selling'|Total of 'projected_micro_loan_cross_selling'|Total of 'projected_share_margin_financing_cross_selling'",
  'kpi_name': 'Projected Education\xa0Loan Penetration Value|Projected Hire Purchase Penetration Value|Projected Home Loan Penetration Value|Projected Personal Loan  Penetration Value|Projected Micro Loan Penetration Value|Projected Share Margin Financing Penetration Value',
  'last_metadata_update': '2024-10-19 01:02:13',
  'number_of_columns': '58',
  'primary_key': 'N/A',
  'row_description': ' The row represents a 49-year-old Malaysian male architect with a credit limit of RM 4009.55, who has a home loan and is currently in his first month of a hire-purchase plan. He has been cross-sold RM 254516.15 worth of share margin financing, and has a projected credit limit of RM 8,129,965.96. The data is from September 2015.',
  'source': 'N/A',
  'sql_database_name': 'MySQL',
  'table_description': ' Table loan_product_penetration_value_randomized_v2 tracks current and projected cross-selling values for various loan products and credit limits, organized by customer demographics. Its columns include age, gender, nationality, race, religion, state, occupation, and other customer attributes. The table also features multiple current and projected cross-selling and penetration values for education loans, hire purchase loans, home loans, micro loans, personal loans, and share margin financing. This information assists in analyzing loan product penetration and optimizing cross-selling strategies within the system.',
  'table_description_v2': ' The "loan_product_penetration_value_randomized_v2" table stores vital data on current and forecasted cross-selling loan products and credit limits. This table enables the extraction of loan product penetration values, facilitating informed decision-making and strategic planning within the business context.',
  'table_name': 'loan_product_penetration_value_randomized_v2',
  'table_short_description': 'Table "loan_product_penetration_value_randomized_v2" tracks current and projected cross-selling values for various loan products, organized by customer demographics, aiding in analyzing loan product penetration and optimizing cross-selling strategies.',
  'table_type': 'DIMENSION'},
 {'column_list': 'age|age_group|cid|city|disability_status|education|education_level|employment_status|frequency|frequency_score|frequency_segment|gender|has_credit_card|has_current_account|has_debit_card|has_loan|income_level|income_range|marital_status|monetary_score|monetary_segment|monetary_value|nationality|no_dependents|occupation|occupation_industry|phone_number|postcode|race|recency|recency_score|recency_segment|religion|rfm_score|rfm_segment|state|transaction_month|transaction_year',
  'database_identifier': 'label1',
  'database_name': 'ada_banks_data_asset',
  'foreign_key': 'N/A',
  'kpi_formula': '(Count of customers group by customer_segment) / total count of customers|(Count of customers group by customer_segment) / total count of customers|(Count of customers group by recency_segment)|(Count of customers group by frequency_segment)|(Count of customers group by monetary_segment)',
  'kpi_name': 'RFM (Recency Frequency Monetary) segment percentage|Number of customer by RFM segment|Customer by Recency segment (how recent customer transact)|Customer by Frequency segment (how frequent customer transact)|Customer by Monetary segment (how much amount customer transact)',
  'last_metadata_update': '2024-10-19 01:02:13',
  'number_of_columns': '38',
  'primary_key': 'N/A',
  'row_description': ' The row represents a 49-year-old male customer from Kampar, Malaysia, with a high-value RFM score, married, and employed in the construction industry. He has a monthly income of RM 10,000 - RM 29,999, has a credit card and a current account, and made a transaction in February 2023.',
  'source': 'N/A',
  'sql_database_name': 'MySQL',
  'table_description': ' The "customer_rfm_demo_product_new" table stores comprehensive customer data, including transactional behavior, demographic information, and product usage, for RFM (Recency, Frequency, Monetary) analysis. This table plays a crucial role in segmenting customers based on their recency, frequency, and monetary value, as well as personal attributes and product interactions. By utilizing this data, businesses can gain valuable insights to drive targeted marketing and enhance customer relationship management strategies. Columns include age, gender, income level, occupation, and various other demographic and behavioral factors.',
  'table_description_v2': " The 'customer_rfm_demo_product_new' table stores integrated data for RFM analysis, customer demographics, and product usage. This comprehensive resource facilitates segmentation of customers based on transactional behavior, personal attributes, and product interactions, ultimately enabling targeted marketing initiatives and enhancing customer relationship management.",
  'table_name': 'customer_rfm_demo_product_new',
  'table_short_description': 'The "customer_rfm_demo_product_new" table stores comprehensive customer data for RFM analysis, crucial for segmenting customers and enhancing CRM strategies.',
  'table_type': 'DIMENSION'},
 {'column_list': 'age|age_group|cid|city|demographic_table_id|disability_status|disaster_name|disaster_table_id|education|gender|id|income_level|income_range|marital_status|nationality|no_dependents|occupation|phone_number|postcode|race|recomended_insurance|recomended_loan|religion|state',
  'database_identifier': 'label1',
  'database_name': 'ada_banks_data_asset',
  'foreign_key': 'N/A',
  'kpi_formula': '(Count of customers with recommended_loan = 1)|(Count of customers with recommended_insurance = 1)|(Count of customers with recomended_insurance = 1) / total count of customers|(Count of customers with recomended_loan = 1) / total count of customers|(Count of customers group by disaster_name)',
  'kpi_name': 'Number of opportunity for loan for area impacted by disaster|Number of opportunity for insurance for area impacted by disaster|Percentage Oppurtunity Product Natural Disaster for Insurance|Percentage Oppurtunity Product Natural Disaster for Loan|Number of people affected by disaster (flood, tsunami, earthquake, etc.)',
  'last_metadata_update': '2024-10-19 01:02:13',
  'number_of_columns': '24',
  'primary_key': "['id']",
  'row_description': ' The row represents a 58-year-old woman from Teluk Intan, Malaysia, who is an architect with no dependents, married, and of Malay race. She has a degree, falls under the very low-income category, and practices Islam. She is from the city of Perak and has not been affected by the flood disaster with ID 565.',
  'source': 'N/A',
  'sql_database_name': 'MySQL',

# Check Column Level Metadata

In [2]:
import chromadb
import numpy as np
from chromadb.config import Settings

embedding_dummy = np.random.randn(1024).tolist()

chromadb_setting = Settings(
    chroma_client_auth_provider="chromadb.auth.basic_authn.BasicAuthClientProvider",
    chroma_client_auth_credentials="userdata:userdataChromaPassw0rd",
)

client2 = chromadb.HttpClient(
    host="52.187.106.203",
    port=8000,
    settings=chromadb_setting,
)

# collection_name = "test.saraswatibrahmaputra.mvp2Test1.columnLevel"
collection_name = "devtest4.ADA.banking.columnLevel"  # dev.ada-app.ai

tbl_collection = client2.get_collection(collection_name)

print(f"Collection: {collection_name}")
print(f"Number of Vectors: {tbl_collection.count()}")

tbl_collection.get(
    # embedding_dummy,
    # limit=tbl_collection.count(),
    # include=["metadatas", "documents", "embeddings"]
    where={
        # "database_name": "starhub_data_asset",
        # "sql_path": "starhub_data_asset.data_asset_001_forecast"
    }
)["metadatas"]

Collection: devtest4.ADA.banking.columnLevel
Number of Vectors: 668

[{'10_samples': '18|19|20|21|22|23|24|25|26|27',
  'all_samples': '18|19|20|21|22|23|24|25|26|27|28|29|30|31|32|33|34|35|36|37|38|39|40|41|42|43|44|45|46|47|48|49|50|51|52|53|54|55|56|57|58|59|60|61|62|63|64|66|67|68|69|70|71|72|73|74|75|76|77|78|79|80',
  'avg_value': 48.74,
  'cleaned_column_name': 'age',
  'column_description': 'Age of the customer as in 2024',
  'column_name_t3': 'Age',
  'data_dictionary_flag': 'None',
  'data_tribe': 'numerical',
  'database_name': 'ada_banks_data_asset',
  'date_format': 'N/A',
  'db_identifier': 'label1',
  'final_kpi_column_match': '',
  'kpi_def_from': '',
  'long_description': "Age of the customer, representing the individual's age in years, which can help in understanding the customer's age distribution and preferences in the product map.",
  'max_value': 80.0,
  'min_value': 18.0,
  'n_unique': 62,
  'n_unique_per_row_count': 5.424302977067447e-05,
  'original_sql_column_name': 'age',
  'pct_null_values': 0.0,
  'possible_values': 'None',
  'row_count': 1143004,
  'sql_data_type': 'bigint',
  'sql_path': 'ada_banks_data_asset.customer_user_journey_product_map_new',
  'sql_path_original_column_name': 'ada_banks_data_asset.customer_user_journey_product_map_new.age',
  'sql_tool_name': 'MySQL',
  'std_value': 18.22,
  'table_name': 'customer_user_journey_product_map_new',
  'universal_all_samples': '18|19|20|21|22|23|24|25|26|27|28|29|30|31|32|33|34|35|36|37|38|39|40|41|42|43|44|45|46|47|48|49|50|51|52|53|54|55|56|57|58|59|60|61|62|63|64|66|67|68|69|70|71|72|73|74|75|76|77|78|79|80'},
 {'10_samples': '0|1',
  'all_samples': '0|1',
  'avg_value': 0.5,
  'cleaned_column_name': 'has_credit_card',
  'column_description': 'Indicates whether the customer has a credit card',
  'column_name_t3': 'Has Credit Card',
  'data_dictionary_flag': 'None',
  'data_tribe': 'categorical',
  'database_name': 'ada_banks_data_asset',
  'date_format': 'N/A',
  'db_identifier': 'label1',
  'final_kpi_column_match': '',
  'kpi_def_from': '',
  'long_description': 'Indicates if the customer possesses a credit card, helping to understand customer payment preferences and enabling tailored financial product offerings.',
  'max_value': 1.0,
  'min_value': 0.0,
  'n_unique': 2,
  'n_unique_per_row_count': 1.7497751538927248e-06,
  'original_sql_column_name': 'has_credit_card',
  'pct_null_values': 0.0,
  'possible_values': 'None',
  'row_count': 1143004,
  'sql_data_type': 'tinyint(1)',
  'sql_path': 'ada_banks_data_asset.customer_user_journey_product_map_new',
  'sql_path_original_column_name': 'ada_banks_data_asset.customer_user_journey_product_map_new.has_credit_card',
  'sql_tool_name': 'MySQL',
  'std_value': 0.5,
  'table_name': 'customer_user_journey_product_map_new',
  'universal_all_samples': '0|1'},
 {'10_samples': 'Argentina|Australia|Bahrain|Bangladesh|Brazil|Canada|China|Egypt|France|Germany',
  'all_samples': 'argentina|australia|bahrain|bangladesh|brazil|canada|china|egypt|france|germany|hong kong|india|indonesia|italy|japan|jordan|kuwait|lebanon|malaysia|mexico|nepal|netherlands|oman|pakistan|philippines|qatar|russia|saudi arabia|singapore|south korea|sri lanka|taiwan|thailand|turkey|ukraine|united arab emirates|united kingdom|united states|vietnam',
  'cleaned_column_name': 'nationality',
  'column_description': "Customer's nationality.",
  'column_name_t3': 'Nationality',
  'data_dictionary_flag': 'None',
  'data_tribe': 'categorical',
  'database_name': 'ada_banks_data_asset',
  'date_format': 'N/A',
  'db_identifier': 'label1',
  'final_kpi_column_match': '',
  'kpi_def_from': '',
  'long_description': 'Nationality helps to understand the geographical distribution of customers and their preferences, supporting international sales and marketing efforts.',
  'n_unique': 39,
  'n_unique_per_row_count': 0.0011780341931976078,
  'original_sql_column_name': 'nationality',
  'pct_null_values': 0.0,
  'possible_values': 'None',
  'row_count': 33106,
  'sql_data_type': 'text',
  'sql_path': 'ada_banks_data_asset.report_cross_selling_performance_cross_sale_value_new',
  'sql_path_original_column_name': 'ada_banks_data_asset.report_cross_selling_performance_cross_sale_value_new.nationality',
  'sql_tool_name': 'MySQL',
  'table_name': 'report_cross_selling_performance_cross_sale_value_new',
  'universal_all_samples': 'argentina|australia|bahrain|bangladesh|brazil|canada|china|egypt|france|germany|hong kong|india|indonesia|italy|japan|jordan|kuwait|lebanon|malaysia|mexico|nepal|netherlands|oman|pakistan|philippines|qatar|russia|saudi arabia|singapore|south korea|sri lanka|taiwan|thailand|turkey|ukraine|united arab emirates|united kingdom|united states|vietnam'},
 {'10_samples': '-174659075.05262998|-19736805.189319015|-15836068.835251257|-13929668.518433793|-12033141.739408921|-10515030.883726943|-7989854.129786245|-7895381.635229693|-7103318.500533103|-6303882.501591259',
  'all_samples': '-174659075.05262998|-19736805.189319015|-15836068.835251257|-13929668.518433793|-12033141.739408921|-10515030.883726943|-7989854.129786245|-7895381.635229693|-7103318.500533103|-6303882.501591259|-6226638.962558398|-5922539.256191572|-4956337.679991486|-4725075.1934032|-4003156.6454339717|-3984021.4050401263|-3935733.8241170375|-3527196.5133440457|-3527040.177397133|-3129983.268393891|-2733177.052375576|-2732884.797544716|-2533828.151960482|-2474686.3927272526|-2336093.4992601215|-1954495.5124751918|-1939161.8555842205|-1938513.4365383876|-1938493.3893978873|-1779925.2218824222|-1621237.234270189|-1542910.4678821205|-1542157.5088445037|-1542112.9365439003|-1542027.4806981527|-1541614.257189866|-1541517.0868201475|-1541456.93078609|-1541317.6360660372|-1541252.9197334591|-1541118.3052580093|-1541099.24643448|-1501464.1552320467|-1382829.8454627683|-1343494.1420299779|-1343035.9811484516|-1312435.0711403624|-1305778.2721157216|-1303143.4830824502|-1224265.52802077|-1224226.90438048|-1223872.2946381634|-1223812.',
  'avg_value': -7080554.51,
  'cleaned_column_name': 'net_cross_sales_value',
  'column_description': 'The net cross sale value of the customer, it is the average total cross sale value against the total cross sale value of the customer.',
  'column_name_t3': 'Net Cross Sales Value',
  'data_dictionary_flag': 'None',
  'data_tribe': 'numerical',
  'database_name': 'ada_banks_data_asset',
  'date_format': 'N/A',
  'db_identifier': 'label1',
  'final_kpi_column_match': '',
  'kpi_def_from': '',
  'long_description': 'Net cross-sales value represents the total value of sales generated from cross-selling initiatives, a critical measure of marketing effectiveness.',
  'max_value': 47057.12033022568,
  'min_value': -174659075.05262998,
  'n_unique': 32260,
  'n_unique_per_row_count': 0.974445719809098,
  'original_sql_column_name': 'net_cross_sales_value',
  'pct_null_values': 0.0,
  'possible_values': 'None',
  'row_count': 33106,
  'sql_data_type': 'double',
  'sql_path': 'ada_banks_data_asset.report_cross_selling_performance_cross_sale_value_new',
  'sql_path_original_column_name': 'ada_banks_data_asset.report_cross_selling_performance_cross_sale_value_new.net_cross_sales_value',
  'sql_tool_name': 'MySQL',
  'std_value': 23575028.99,
  'table_name': 'report_cross_selling_performance_cross_sale_value_new',
  'universal_all_samples': '-174659075.05262998|-19736805.189319015|-15836068.835251257|-13929668.518433793|-12033141.739408921|-10515030.883726943|-7989854.129786245|-7895381.635229693|-7103318.500533103|-6303882.501591259|-6226638.962558398|-5922539.256191572|-4956337.679991486|-4725075.1934032|-4003156.6454339717|-3984021.4050401263|-3935733.8241170375|-3527196.5133440457|-3527040.177397133|-3129983.268393891|-2733177.052375576|-2732884.797544716|-2533828.151960482|-2474686.3927272526|-2336093.4992601215|-1954495.5124751918|-1939161.8555842205|-1938513.4365383876|-1938493.3893978873|-1779925.2218824222|-1621237.234270189|-1542910.4678821205|-1542157.5088445037|-1542112.9365439003|-1542027.4806981527|-1541614.257189866|-1541517.0868201475|-1541456.93078609|-1541317.6360660372|-1541252.9197334591|-1541118.3052580093|-1541099.24643448|-1501464.1552320467|-1382829.8454627683|-1343494.1420299779|-1343035.9811484516|-1312435.0711403624|-1305778.2721157216|-1303143.4830824502|-1224265.52802077|-1224226.90438048|-1223872.2946381634|-1223812.'},
 {'10_samples': '0|1|2|3|4|5|6|7|8|9',
  'all_samples': '0|1|2|3|4|5|6|7|8|9|10',
  'avg_value': 5.0,
  'cleaned_column_name': 'no_dependents',
  'column_description': "Customer's financial dependencies by number of person.",
  'column_name_t3': 'Number of Dependents',
  'data_dictionary_flag': 'None',
  'data_tribe': 'numerical',
  'database_name': 'ada_banks_data_asset',
  'date_format': 'N/A',
  'db_identifier': 'label1',
  'final_kpi_column_match': '',
  'kpi_def_from': '',
  'long_description': 'No dependents indicates the number of dependents a customer has, contributing to profiling customers for targeted marketing and sales campaigns.',
  'max_value': 10.0,
  'min_value': 0.0,
  'n_unique': 11,
  'n_unique_per_row_count': 0.00033226605449163295,
  'original_sql_column_name': 'no_dependents',
  'pct_null_values': 0.0,
  'possible_values': 'None',
  'row_count': 33106,
  'sql_data_type': 'bigint',
  'sql_path': 'ada_banks_data_asset.report_cross_selling_performance_cross_sale_value_new',
  'sql_path_original_column_name': 'ada_banks_data_asset.report_cross_selling_performance_cross_sale_value_new.no_dependents',
  'sql_tool_name': 'MySQL',
  'std_value': 3.16,
  'table_name': 'report_cross_selling_performance_cross_sale_value_new',
  'universal_all_samples': '0|1|2|3|4|5|6|7|8|9|10'},
 {'10_samples': 'Accountant|Actor|Actuary|Agricultural technician|Agronomist|Aquaculture specialist|Architect|Artist|Assembly line worker|Banker',
  'all_samples': 'accountant|actor|actuary|agricultural technician|agronomist|aquaculture specialist|architect|artist|assembly line worker|banker|broadcast engineer|chef|civil engineer|construction foreman|consultant|curriculum developer|customer service manager|customs broker|customs officer|cybersecurity analyst|data scientist|delivery driver|doctor|drilling supervisor|e-commerce specialist|education consultant|electrical engineer|energy analyst|engineer (various fields)|environmental engineer|environmental scientist|event coordinator|event manager|executive assistant|farm manager|field engineer|financial analyst|financial planner|fisheries officer|fitness instructor|food & beverage supervisor|freight coordinator|front desk executive|gas technician|geologist|government officer|graphic designer|hotel manager|housekeeping supervisor|human resource manager|industrial engineer|insurance underwriter|inventory manager|investment analyst|it support specialist|law enforcement officer|lawyer|leasing consultant|librarian|loan officer|',
  'cleaned_column_name': 'occupation',
  'column_description': "Customer's occupation.",
  'column_name_t3': 'Occupation',
  'data_dictionary_flag': 'None',
  'data_tribe': 'categorical',
  'database_name': 'ada_banks_data_asset',
  'date_format': 'N/A',
  'db_identifier': 'label1',
  'final_kpi_column_match': '',
  'kpi_def_from': '',
  'long_description': 'Occupation helps categorize customers based on their profession, supporting segmentation and tailored marketing strategies.',
  'n_unique': 121,
  'n_unique_per_row_count': 0.0036549265994079622,
  'original_sql_column_name': 'occupation',
  'pct_null_values': 0.0,
  'possible_values': 'None',
  'row_count': 33106,
  'sql_data_type': 'text',
  'sql_path': 'ada_banks_data_asset.report_cross_selling_performance_cross_sale_value_new',
  'sql_path_original_column_name': 'ada_banks_data_asset.report_cross_selling_performance_cross_sale_value_new.occupation',
  'sql_tool_name': 'MySQL',
  'table_name': 'report_cross_selling_performance_cross_sale_value_new',
  'universal_all_samples': 'accountant|actor|actuary|agricultural technician|agronomist|aquaculture specialist|architect|artist|assembly line worker|banker|broadcast engineer|chef|civil engineer|construction foreman|consultant|curriculum developer|customer service manager|customs broker|customs officer|cybersecurity analyst|data scientist|delivery driver|doctor|drilling supervisor|e-commerce specialist|education consultant|electrical engineer|energy analyst|engineer (various fields)|environmental engineer|environmental scientist|event coordinator|event manager|executive assistant|farm manager|field engineer|financial analyst|financial planner|fisheries officer|fitness instructor|food & beverage supervisor|freight coordinator|front desk executive|gas technician|geologist|government officer|graphic designer|hotel manager|housekeeping supervisor|human resource manager|industrial engineer|insurance underwriter|inventory manager|investment analyst|it support specialist|law enforcement officer|lawyer|leasing consultant|librarian|loan officer|'},
 {'10_samples': '+60100000829|+60100002303|+60100004771|+60100007531|+60100007625|+60100008161|+60100013715|+60100015184|+60100019422|+60100023506',
  'all_samples': '+60100000829|+60100002303|+60100004771|+60100007531|+60100007625|+60100008161|+60100013715|+60100015184|+60100019422|+60100023506|+60100024565|+60100027881|+60100030626|+60100030688|+60100030884|+60100032598|+60100033190|+60100045313|+60100048685|+60100050639|+60100052210|+60100058295|+60100065241|+60100066838|+60100067828|+60100068203|+60100068504|+60100069973|+60100070381|+60100070661|+60100071936|+60100076005|+60100077611|+60100078664|+60100084002|+60100088772|+60100089769|+60100100693|+60100100794|+60100102234|+60100104331|+60100104337|+60100108757|+60100113265|+60100115984|+60100120724|+60100121123|+60100124136|+60100124945|+60100126661|+60100131070|+60100139075|+60100154350|+60100154456|+60100162842|+60100164043|+60100164108|+60100166916|+60100168475|+60100169948|+60100182032|+60100182723|+60100183261|+60100183657|+60100183751|+60100186051|+60100188064|+60100190236|+60100196669|+60100200085|+60100200158|+60100202678|+60100204413|+60100206322|+60100210660|+60100213990|+60100215269|+60100229979|+601002387',
  'avg_value': 59346953021.03,
  'cleaned_column_name': 'phone_number',
  'column_description': 'Customer personal phone number.',
  'column_name_t3': 'Phone Number',
  'data_dictionary_flag': 'None',
  'data_tribe': 'id',
  'database_name': 'ada_banks_data_asset',
  'date_format': 'N/A',
  'db_identifier': 'label1',
  'final_kpi_column_match': '',
  'kpi_def_from': '',
  'long_description': 'Phone number is a contact detail for customers, allowing for direct communication and personalized customer service.',
  'max_value': 60100229979.0,
  'min_value': 99999999.99,
  'n_unique': 33100,
  'n_unique_per_row_count': 0.9998187639702772,
  'original_sql_column_name': 'phone_number',
  'pct_null_values': 0.0,
  'possible_values': 'None',
  'row_count': 33106,
  'sql_data_type': 'text',
  'sql_path': 'ada_banks_data_asset.report_cross_selling_performance_cross_sale_value_new',
  'sql_path_original_column_name': 'ada_banks_data_asset.report_cross_selling_performance_cross_sale_value_new.phone_number',
  'sql_tool_name': 'MySQL',
  'std_value': 6651669075.52,
  'table_name': 'report_cross_selling_performance_cross_sale_value_new',
  'universal_all_samples': '+60100000829|+60100002303|+60100004771|+60100007531|+60100007625|+60100008161|+60100013715|+60100015184|+60100019422|+60100023506|+60100024565|+60100027881|+60100030626|+60100030688|+60100030884|+60100032598|+60100033190|+60100045313|+60100048685|+60100050639|+60100052210|+60100058295|+60100065241|+60100066838|+60100067828|+60100068203|+60100068504|+60100069973|+60100070381|+60100070661|+60100071936|+60100076005|+60100077611|+60100078664|+60100084002|+60100088772|+60100089769|+60100100693|+60100100794|+60100102234|+60100104331|+60100104337|+60100108757|+60100113265|+60100115984|+60100120724|+60100121123|+60100124136|+60100124945|+60100126661|+60100131070|+60100139075|+60100154350|+60100154456|+60100162842|+60100164043|+60100164108|+60100166916|+60100168475|+60100169948|+60100182032|+60100182723|+60100183261|+60100183657|+60100183751|+60100186051|+60100188064|+60100190236|+60100196669|+60100200085|+60100200158|+60100202678|+60100204413|+60100206322|+60100210660|+60100213990|+60100215269|+60100229979|+601002387'},
 {'10_samples': '01000|01100|02000|02100|02600|05000|05100|05200|05300|05400',
  'all_samples': '01000|01100|02000|02100|02600|05000|05100|05200|05300|05400|05500|06000|07000|07100|08000|08100|08300|09000|09100|09300|10000|10100|10200|10300|10400|11000|11900|11950|12000|12100|12200|14000|14100|14200|15000|15100|15200|15300|15400|15500|15600|16000|16070|17000|17500|18300|18500|20000|20100|21600|22000|23000|24000|25000|25100|25200|25300|25500|26600|27000|27600|28000|28700|30000|30100|30200|30300|30450|30500|31500|31900|32200|33000|34000|34600|36000|36100|39000|40000|40100|40200|41000|41100|46000|46100|46200|47500|48000|50000|50100|50200|50300|50400|50500|50600|50700|50800|53300|53400|55100|56000|56100|59000|62000|62100|62200|62300|62400|62500|68000|68100|70000|70100|70200|70300|71000|71050|71300|71600|71800|71900|73000|75000|75100|75200|75300|75400|75450|75500|77000|77100|78000|78300|80000|80100|80200|80300|80400|80500|80600|80700|80990|81000|81100|81300|81900|82000|83000|83100|84000|84150|84900|85000|85100|86000|86100|86200|87000|87100|88000|88100|88200|88300|88400|89000|89300|89800|90000|90100|91000|9110',
  'avg_value': 45997.78,
  'cleaned_column_name': 'postcode',
  'column_description': 'Customer residential postcode.',
  'column_name_t3': 'Postal Code',
  'data_dictionary_flag': 'None',
  'data_tribe': 'categorical',
  'database_name': 'ada_banks_data_asset',
  'date_format': 'N/A',
  'db_identifier': 'label1',
  'final_kpi_column_match': '',
  'kpi_def_from': '',
  'long_description': 'Postcode identifies the specific region or neighborhood where customers reside, aiding in location-based market analysis and sales strategies.',
  'max_value': 98700.0,
  'min_value': 1000.0,
  'n_unique': 184,
  'n_unique_per_row_count': 0.005557904911496405,
  'original_sql_column_name': 'postcode',
  'pct_null_values': 0.0,
  'possible_values': 'None',
  'row_count': 33106,
  'sql_data_type': 'text',
  'sql_path': 'ada_banks_data_asset.report_cross_selling_performance_cross_sale_value_new',
  'sql_path_original_column_name': 'ada_banks_data_asset.report_cross_selling_performance_cross_sale_value_new.postcode',
  'sql_tool_name': 'MySQL',
  'std_value': 29471.03,
  'table_name': 'report_cross_selling_performance_cross_sale_value_new',
  'universal_all_samples': '01000|01100|02000|02100|02600|05000|05100|05200|05300|05400|05500|06000|07000|07100|08000|08100|08300|09000|09100|09300|10000|10100|10200|10300|10400|11000|11900|11950|12000|12100|12200|14000|14100|14200|15000|15100|15200|15300|15400|15500|15600|16000|16070|17000|17500|18300|18500|20000|20100|21600|22000|23000|24000|25000|25100|25200|25300|25500|26600|27000|27600|28000|28700|30000|30100|30200|30300|30450|30500|31500|31900|32200|33000|34000|34600|36000|36100|39000|40000|40100|40200|41000|41100|46000|46100|46200|47500|48000|50000|50100|50200|50300|50400|50500|50600|50700|50800|53300|53400|55100|56000|56100|59000|62000|62100|62200|62300|62400|62500|68000|68100|70000|70100|70200|70300|71000|71050|71300|71600|71800|71900|73000|75000|75100|75200|75300|75400|75450|75500|77000|77100|78000|78300|80000|80100|80200|80300|80400|80500|80600|80700|80990|81000|81100|81300|81900|82000|83000|83100|84000|84150|84900|85000|85100|86000|86100|86200|87000|87100|88000|88100|88200|88300|88400|89000|89300|89800|90000|90100|91000|9110'},
 {'10_samples': 'Ae|Ag|Ah|Am|Aq|B0|B1|B2|B6|B7',

# Check Sample Level Metadata

In [3]:
import chromadb
import numpy as np
from chromadb.config import Settings

embedding_dummy = np.random.randn(1024).tolist()

chromadb_setting = Settings(
    chroma_client_auth_provider="chromadb.auth.basic_authn.BasicAuthClientProvider",
    chroma_client_auth_credentials="userdata:userdataChromaPassw0rd",
)

client2 = chromadb.HttpClient(
    host="52.187.106.203",
    port=8000,
    settings=chromadb_setting,
)

# collection_name = "test.saraswatibrahmaputra.mvp2Test1.columnLevel"
collection_name = "devtest3.ADA.banking.samples"

tbl_collection = client2.get_collection(collection_name)

print(f"Collection: {collection_name}")
print(f"Number of Vectors: {tbl_collection.count()}")

tbl_collection.get(
    # embedding_dummy,
    # limit=tbl_collection.count(),
    # include=["metadatas", "documents", "embeddings"]
    where={
        # "database_name": "starhub_data_asset",
        # "sql_path": "starhub_data_asset.data_asset_001_forecast"
    }
)["metadatas"]

Collection: devtest3.ADA.banking.samples
Number of Vectors: 690

[{'10_samples': '1|2|3|4|5|6|7|8|9|10',
  'all_samples': '1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31|32|33|34|35|36|37|38|39|40|41|42|43|44|45|46|47|48|49|50|51|52|53|54|55|56|57|58|59|60|61|62|63|64|65|66|67|68|69|70|71|72|73|74|75|76|77|78|79|80|81|82|83|84|85|86|87|88|89|90|91|92|93|94|95|96|97|98|99|100|101|102|103|104|105|106|107|108|109|110|111|112|113|114|115|116|117|118|119|120|121|122|123|124|125|126|127|128|129|130|131|132|133|134|135|136|137|138|139|140|141|142|143|144|145|146|147|148|149|150|151|152|153|154|155|156|157|158|159|160|161|162|163|164|165|166|167|168|169|170|171|172|173|174|175|176|177|178|179|180|181|182|183|184|185|186|187|188|189|190|191|192|193|194|195|196|197|198|199|200|201|202|203|204|205|206|207|208|209|210|211|212|213|214|215|216|217|218|219|220|221|222|223|224|225|226|227|228|229|230|231|232|233|234|235|236|237|238|239|240|241|242|243|244|245|246|247|248|249|250|251|252|253|254|255|256|257|258|259|260|261|262|263|264|265|266|267|268|269|270|271|272|273|274|275|276|277|278|279|280|281|282|283|',
  'cleaned_column_name': 'ID',
  'data_tribe': 'id',
  'database_name': 'ada_banks_data_asset',
  'original_sql_column_name': 'ID',
  'sql_path': 'ada_banks_data_asset.report_cross_selling_performance_product_type_new',
  'sql_path_original_column_name': 'ada_banks_data_asset.report_cross_selling_performance_product_type_new.ID',
  'table_name': 'report_cross_selling_performance_product_type_new',
  'universal_all_samples': '1|2|3|4|5|6|7|8|9|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31|32|33|34|35|36|37|38|39|40|41|42|43|44|45|46|47|48|49|50|51|52|53|54|55|56|57|58|59|60|61|62|63|64|65|66|67|68|69|70|71|72|73|74|75|76|77|78|79|80|81|82|83|84|85|86|87|88|89|90|91|92|93|94|95|96|97|98|99|100|101|102|103|104|105|106|107|108|109|110|111|112|113|114|115|116|117|118|119|120|121|122|123|124|125|126|127|128|129|130|131|132|133|134|135|136|137|138|139|140|141|142|143|144|145|146|147|148|149|150|151|152|153|154|155|156|157|158|159|160|161|162|163|164|165|166|167|168|169|170|171|172|173|174|175|176|177|178|179|180|181|182|183|184|185|186|187|188|189|190|191|192|193|194|195|196|197|198|199|200|201|202|203|204|205|206|207|208|209|210|211|212|213|214|215|216|217|218|219|220|221|222|223|224|225|226|227|228|229|230|231|232|233|234|235|236|237|238|239|240|241|242|243|244|245|246|247|248|249|250|251|252|253|254|255|256|257|258|259|260|261|262|263|264|265|266|267|268|269|270|271|272|273|274|275|276|277|278|279|280|281|282|283|'},
 {'10_samples': 'False|True',
  'all_samples': 'false|true',
  'cleaned_column_name': 'has_credit_card',
  'data_tribe': 'categorical',
  'database_name': 'ada_banks_data_asset',
  'original_sql_column_name': 'has_credit_card',
  'sql_path': 'ada_banks_data_asset.report_cross_selling_performance_product_type_new',
  'sql_path_original_column_name': 'ada_banks_data_asset.report_cross_selling_performance_product_type_new.has_credit_card',
  'table_name': 'report_cross_selling_performance_product_type_new',
  'universal_all_samples': 'false|true'},
 {'10_samples': 'False|True',
  'all_samples': 'false|true',
  'cleaned_column_name': 'has_current_account',
  'data_tribe': 'categorical',
  'database_name': 'ada_banks_data_asset',
  'original_sql_column_name': 'has_current_account',
  'sql_path': 'ada_banks_data_asset.report_cross_selling_performance_product_type_new',
  'sql_path_original_column_name': 'ada_banks_data_asset.report_cross_selling_performance_product_type_new.has_current_account',
  'table_name': 'report_cross_selling_performance_product_type_new',
  'universal_all_samples': 'false|true'},
 {'10_samples': 'False|True',
  'all_samples': 'false|true',
  'cleaned_column_name': 'has_debit_card',
  'data_tribe': 'categorical',
  'database_name': 'ada_banks_data_asset',
  'original_sql_column_name': 'has_debit_card',
  'sql_path': 'ada_banks_data_asset.report_cross_selling_performance_product_type_new',
  'sql_path_original_column_name': 'ada_banks_data_asset.report_cross_selling_performance_product_type_new.has_debit_card',
  'table_name': 'report_cross_selling_performance_product_type_new',
  'universal_all_samples': 'false|true'},
 {'10_samples': 'False|True',
  'all_samples': 'false|true',
  'cleaned_column_name': 'has_loan',
  'data_tribe': 'categorical',
  'database_name': 'ada_banks_data_asset',
  'original_sql_column_name': 'has_loan',
  'sql_path': 'ada_banks_data_asset.report_cross_selling_performance_product_type_new',
  'sql_path_original_column_name': 'ada_banks_data_asset.report_cross_selling_performance_product_type_new.has_loan',
  'table_name': 'report_cross_selling_performance_product_type_new',
  'universal_all_samples': 'false|true'},
 {'10_samples': 'High income|Low income|Lower-middle income|Upper-middle income|Very low income',
  'all_samples': 'high income|low income|lower-middle income|upper-middle income|very low income',
  'cleaned_column_name': 'income_level',
  'data_tribe': 'categorical',
  'database_name': 'ada_banks_data_asset',
  'original_sql_column_name': 'income_level',
  'sql_path': 'ada_banks_data_asset.report_cross_selling_performance_product_type_new',
  'sql_path_original_column_name': 'ada_banks_data_asset.report_cross_selling_performance_product_type_new.income_level',
  'table_name': 'report_cross_selling_performance_product_type_new',
  'universal_all_samples': 'high income|low income|lower-middle income|upper-middle income|very low income'},
 {'10_samples': 'Above rm 30,000|Below rm 2,499|Rm 10,000 - rm 29,999|Rm 2,500 - rm 4,999|Rm 5,000 - rm 9,999',
  'all_samples': 'above rm 30,000|below rm 2,499|rm 10,000 - rm 29,999|rm 2,500 - rm 4,999|rm 5,000 - rm 9,999',
  'cleaned_column_name': 'income_range',
  'data_tribe': 'categorical',
  'database_name': 'ada_banks_data_asset',
  'original_sql_column_name': 'income_range',
  'sql_path': 'ada_banks_data_asset.report_cross_selling_performance_product_type_new',
  'sql_path_original_column_name': 'ada_banks_data_asset.report_cross_selling_performance_product_type_new.income_range',
  'table_name': 'report_cross_selling_performance_product_type_new',
  'universal_all_samples': 'above rm 30,000|below rm 2,499|rm 10,000 - rm 29,999|rm 2,500 - rm 4,999|rm 5,000 - rm 9,999'},
 {'10_samples': '18|19|20|21|22|23|24|25|26|27',
  'all_samples': '18|19|20|21|22|23|24|25|26|27|28|29|30|31|32|33|34|35|36|37|38|39|40|41|42|43|44|45|46|47|48|49|50|51|52|53|54|55|56|57|58|59|60|61|62|63|64|66|67|68|69|70|71|72|73|74|75|76|77|78|79|80',
  'cleaned_column_name': 'age',
  'data_tribe': 'numerical',
  'database_name': 'ada_banks_data_asset',
  'original_sql_column_name': 'age',
  'sql_path': 'ada_banks_data_asset.customer_user_journey_product_map_new',
  'sql_path_original_column_name': 'ada_banks_data_asset.customer_user_journey_product_map_new.age',
  'table_name': 'customer_user_journey_product_map_new',
  'universal_all_samples': '18|19|20|21|22|23|24|25|26|27|28|29|30|31|32|33|34|35|36|37|38|39|40|41|42|43|44|45|46|47|48|49|50|51|52|53|54|55|56|57|58|59|60|61|62|63|64|66|67|68|69|70|71|72|73|74|75|76|77|78|79|80'},
 {'10_samples': '18-20|21-25|26-30|31-35|36-40|41-45|46-50|51-55|56-60|61-65',
  'all_samples': '18-20|21-25|26-30|31-35|36-40|41-45|46-50|51-55|56-60|61-65|66-70|70+',
  'cleaned_column_name': 'age_group',
  'data_tribe': 'categorical',
  'database_name': 'ada_banks_data_asset',
  'original_sql_column_name': 'age_group',
  'sql_path': 'ada_banks_data_asset.customer_user_journey_product_map_new',
  'sql_path_original_column_name': 'ada_banks_data_asset.customer_user_journey_product_map_new.age_group',
  'table_name': 'customer_user_journey_product_map_new',
  'universal_all_samples': '18-20|21-25|26-30|31-35|36-40|41-45|46-50|51-55|56-60|61-65|66-70|70+'},
 {'10_samples': '0000011421537092|0000065823848918|0000112389390579|0000182138820197|0000255128286920|0000301986614090|0000350321525042|0000360550631890|0000384834566981|0000424759033264',
  'all_samples': '0000011421537092|0000065823848918|0000112389390579|0000182138820197|0000255128286920|0000301986614090|0000350321525042|0000360550631890|0000384834566981|0000424759033264|0000425351196211|0000434225139576|0000484985321822|0000508465329822|0000509115862280|0000518416723051|0000531905763311|0000537556061998|0000636479002356|0000730423900910|0000848830780240|0000868737579820|0000887825772246|0000895020320153|0001002761355546|0001021124793303|0001089099395706|0001120534799504|0001154216829319|0001186729904943|0001278920517342|0001345959169133|0001346113729226|0001446189079456|0001541665108970|0001584597624619|0001665445356572|0001692164124777|0001753474526652|0001816123437062|0001842069230577|0001883943600747|0001899277955658|0001931896750905|0001944033408743|0002152149224165|0002353815348638|0002359660103848|0002393143646526|0002393816303338|0002396463062938|0002398219373160|0002414282195405|0002465481422898|0002471368475542|0002617656523379|0002620244063569|0002626196196557|0002629581231016|0002663817289969|0002',
  'cleaned_column_name': 'cid',
  'data_tribe': 'id',
  'database_name': 'ada_banks_data_asset',
  'original_sql_column_name': 'cid',
  'sql_path': 'ada_banks_data_asset.customer_user_journey_product_map_new',
  'sql_path_original_column_name': 'ada_banks_data_asset.customer_user_journey_product_map_new.cid',
  'table_name': 'customer_user_journey_product_map_new',
  'universal_all_samples': '0000011421537092|0000065823848918|0000112389390579|0000182138820197|0000255128286920|0000301986614090|0000350321525042|0000360550631890|0000384834566981|0000424759033264|0000425351196211|0000434225139576|0000484985321822|0000508465329822|0000509115862280|0000518416723051|0000531905763311|0000537556061998|0000636479002356|0000730423900910|0000848830780240|0000868737579820|0000887825772246|0000895020320153|0001002761355546|0001021124793303|0001089099395706|0001120534799504|0001154216829319|0001186729904943|0001278920517342|0001345959169133|0001346113729226|0001446189079456|0001541665108970|0001584597624619|0001665445356572|0001692164124777|0001753474526652|0001816123437062|0001842069230577|0001883943600747|0001899277955658|0001931896750905|0001944033408743|0002152149224165|0002353815348638|0002359660103848|0002393143646526|0002393816303338|0002396463062938|0002398219373160|0002414282195405|0002465481422898|0002471368475542|0002617656523379|0002620244063569|0002626196196557|0002629581231016|0002663817289969|0002'},
 {'10_samples': 'Alor gajah|Alor setar|Ampang|Arau|Ayer keroh|Bachok|Balik pulau|Baling|Bangsar|Batu gajah',
  'all_samples': 'alor gajah|alor setar|ampang|arau|ayer keroh|bachok|balik pulau|baling|bangsar|batu gajah|batu pahat|bayan lepas|beaufort|bentong|besut|bintulu|bukit bintang|bukit mertajam|butterworth|cameron highlands|cheras|dungun|george town|gombak|gua musang|ipoh|jasin|jelebu|jerantut|jitra|johor bahru|kampar|kangar|kemaman|keningau|klang|kluang|kota bharu|kota kinabalu|kota tinggi|kuala kangsar|kuala lumpur|kuala perlis|kuala terengganu|kuantan|kuching|kulai|kulim|labuan|lahad datu|langkawi|limbang|lumut|machang|marang|masjid tanah|melaka city|miri|muar|mukah|nilai|padang besar|pasir mas|pekan|petaling jaya|pontian|port dickson|presint 1|presint 2|presint 3|presint 4|presint 5|presint 6|ranau|raub|rawang|rembau|sandakan|segamat|seremban|setapak|shah alam|sibu|subang jaya|sungai petani|taiping|tampin|tanah merah|tangkak|tawau|teluk intan|temerloh|tumpat|wangsa maju',
  'cleaned_column_name': 'city',
  'data_tribe': 'categorical',
  'database_name': 'ada_banks_data_asset',
  'original_sql_column_name': 'city',
  'sql_path': 'ada_banks_data_asset.customer_user_journey_product_map_new',
  'sql_path_original_column_name': 'ada_banks_data_asset.customer_user_journey_product_map_new.city',
  'table_name': 'customer_user_journey_product_map_new',
  'universal_all_samples': 'alor gajah|alor setar|ampang|arau|ayer keroh|bachok|balik pulau|baling|bangsar|batu gajah|batu pahat|bayan lepas|beaufort|bentong|besut|bintulu|bukit bintang|bukit mertajam|butterworth|cameron highlands|cheras|dungun|george town|gombak|gua musang|ipoh|jasin|jelebu|jerantut|jitra|johor bahru|kampar|kangar|kemaman|keningau|klang|kluang|kota bharu|kota kinabalu|kota tinggi|kuala kangsar|kuala lumpur|kuala perlis|kuala terengganu|kuantan|kuching|kulai|kulim|labuan|lahad datu|langkawi|limbang|lumut|machang|marang|masjid tanah|melaka city|miri|muar|mukah|nilai|padang besar|pasir mas|pekan|petaling jaya|pontian|port dickson|presint 1|presint 2|presint 3|presint 4|presint 5|presint 6|ranau|raub|rawang|rembau|sandakan|segamat|seremban|setapak|shah alam|sibu|subang jaya|sungai petani|taiping|tampin|tanah merah|tangkak|tawau|teluk intan|temerloh|tumpat|wangsa maju'},
 {'10_samples': 'No|Yes',
  'all_samples': 'no|yes',
  'cleaned_column_name': 'loan',
  'data_tribe': 'categorical',
  'database_name': 'ada_banks_data_asset',
  'original_sql_column_name': 'loan',
  'sql_path': 'ada_banks_data_asset.report_cross_selling_performance_product_type_new',
  'sql_path_original_column_name': 'ada_banks_data_asset.report_cross_selling_performance_product_type_new.loan',
  'table_name': 'report_cross_selling_performance_product_type_new',
  'universal_all_samples': 'no|yes'},
 {'10_samples': '0|1',
  'all_samples': '0|1',
  'cleaned_column_name': 'disability_status',
  'data_tribe': 'categorical',
  'database_name': 'ada_banks_data_asset',
  'original_sql_column_name': 'disability_status',
  'sql_path': 'ada_banks_data_asset.customer_user_journey_product_map_new',
  'sql_path_original_column_name': 'ada_banks_data_asset.customer_user_journey_product_map_new.disability_status',
  'table_name': 'customer_user_journey_product_map_new',
  'universal_all_samples': '0|1'},
 {'10_samples': 'Degree|Diploma|Master|Others|Phd|Spm|Stpm',
  'all_samples': 'degree|diploma|master|others|phd|spm|stpm',
  'cleaned_column_name': 'education',
  'data_tribe': 'categorical',
  'database_name': 'ada_banks_data_asset',
  'original_sql_column_name': 'education',
  'sql_path': 'ada_banks_data_asset.customer_user_journey_product_map_new',
  'sql_path_original_column_name': 'ada_banks_data_asset.customer_user_journey_product_map_new.education',
  'table_name': 'customer_user_journey_product_map_new',
  'universal_all_samples': 'degree|diploma|master|others|phd|spm|stpm'},
 {'10_samples': 'Others|Postgraduate education|Secondary education|Undergraduate education',
  'all_samples': 'others|postgraduate education|secondary education|undergraduate education',
  'cleaned_column_name': 'education_level',
  'data_tribe': 'categorical',
  'database_name': 'ada_banks_data_asset',
  'original_sql_column_name': 'education_level',
  'sql_path': 'ada_banks_data_asset.customer_user_journey_product_map_new',
  'sql_path_original_column_name': 'ada_banks_data_asset.customer_user_journey_product_map_new.education_level',
  'table_name': 'customer_user_journey_product_map_new',
  'universal_all_samples': 'others|postgraduate education|secondary education|undergraduate education'},
 {'10_samples': 'Government employed|Private employed|Retired|Self employed|Student|Unemployed',
  'all_samples': 'government employed|private employed|retired|self employed|student|unemployed',
  'cleaned_column_name': 'employment_status',
  'data_tribe': 'categorical',
  'database_name': 'ada_banks_data_asset',
  'original_sql_column_name': 'employment_status',
  'sql_path': 'ada_banks_data_asset.customer_user_journey_product_map_new',
  'sql_path_original_column_name': 'ada_banks_data_asset.customer_user_journey_product_map_new.employment_status',
  'table_name': 'customer_user_journey_product_map_new',
  'universal_all_samples': 'government employed|private employed|retired|self employed|student|unemployed'},
 {'10_samples': 'Female|Male',
  'all_samples': 'female|male',
  'cleaned_column_name': 'gender',
  'data_tribe': 'categorical',
  'database_name': 'ada_banks_data_asset',
  'original_sql_column_name': 'gender',
  'sql_path': 'ada_banks_data_asset.customer_user_journey_product_map_new',
  'sql_path_original_column_name': 'ada_banks_data_asset.customer_user_journey_product_map_new.gender',
  'table_name': 'customer_user_journey_product_map_new',
  'universal_all_samples': 'female|male'},
 {'10_samples': '0|1',
  'all_samples': '0|1',
  'cleaned_column_name': 'has_credit_card',
  'data_tribe': 'categorical',
  'database_name': 'ada_banks_data_asset',
  'original_sql_column_name': 'has_credit_card',
  'sql_path': 'ada_banks_data_asset.customer_user_journey_product_map_new',
  'sql_path_original_column_name': 'ada_banks_data_asset.customer_user_journey_product_map_new.has_credit_card',
  'table_name': 'customer_user_journey_product_map_new',
  'universal_all_samples': '0|1'},
 {'10_samples': '0|1',
  'all_samples': '0|1',
  'cleaned_column_name': 'has_current_account',
  'data_tribe': 'categorical',
  'database_name': 'ada_banks_data_asset',
  'original_sql_column_name': 'has_current_account',
  'sql_path': 'ada_banks_data_asset.customer_user_journey_product_map_new',
  'sql_path_original_column_name': 'ada_banks_data_asset.customer_user_journey_product_map_new.has_current_account',
  'table_name': 'customer_user_journey_product_map_new',
  'universal_all_samples': '0|1'},
 {'10_samples': '0|1',
  'all_samples': '0|1',
  'cleaned_column_name': 'has_debit_card',
  'data_tribe': 'categorical',
  'database_name': 'ada_banks_data_asset',
  'original_sql_column_name': 'has_debit_card',
  'sql_path': 'ada_banks_data_asset.customer_user_journey_product_map_new',
  'sql_path_original_column_name': 'ada_banks_data_asset.customer_user_journey_product_map_new.has_debit_card',
  'table_name': 'customer_user_journey_product_map_new',
  'universal_all_samples': '0|1'},
 {'10_samples': '0|1',
  'all_samples': '0|1',
  'cleaned_column_name': 'has_debit_card_junior',
  'data_tribe': 'categorical',
  'database_name': 'ada_banks_data_asset',
  'original_sql_column_name': 'has_debit_card_junior',
  'sql_path': 'ada_banks_data_asset.customer_user_journey_product_map_new',
  'sql_path_original_column_name': 'ada_banks_data_asset.customer_user_journey_product_map_new.has_debit_card_junior',
  'table_name': 'customer_user_journey_product_map_new',
  'universal_all_samples': '0|1'},
 {'10_samples': 'False|True',
  'all_samples': 'false|true',
  'cleaned_column_name': 'loan_debit_pairing',
  'data_tribe': 'categorical',
  'database_name': 'ada_banks_data_asset',
  'original_sql_column_name': 'loan_debit_pairing',
  'sql_path': 'ada_banks_data_asset.report_cross_selling_performance_product_type_new',
  'sql_path_original_column_name': 'ada_banks_data_asset.report_cross_selling_performance_product_type_new.loan_debit_pairing',
  'table_name': 'report_cross_selling_performance_product_type_new',
  'universal_all_samples': 'false|true'},
 {'10_samples': '0|1',
  'all_samples': '0|1',
  'cleaned_column_name': 'has_debit_card_master',
  'data_tribe': 'categorical',
  'database_name': 'ada_banks_data_asset',
  'original_sql_column_name': 'has_debit_card_master',
  'sql_path': 'ada_banks_data_asset.customer_user_journey_product_map_new',
  'sql_path_original_column_name': 'ada_banks_data_asset.customer_user_journey_product_map_new.has_debit_card_master',
  'table_name': 'customer_user_journey_product_map_new',
  'universal_all_samples': '0|1'},
 {'10_samples': '0|1',
  'all_samples': '0|1',
  'cleaned_column_name': 'has_debit_card_micro',
  'data_tribe': 'categorical',
  'database_name': 'ada_banks_data_asset',
  'original_sql_column_name': 'has_debit_card_micro',
  'sql_path': 'ada_banks_data_asset.customer_user_journey_product_map_new',
  'sql_path_original_column_name': 'ada_banks_data_asset.customer_user_journey_product_map_new.has_debit_card_micro',
  'table_name': 'customer_user_journey_product_map_new',
  'universal_all_samples': '0|1'},
 {'10_samples': '0|1',
  'all_samples': '0|1',
  'cleaned_column_name': 'has_debit_card_visa',
  'data_tribe': 'categorical',
  'database_name': 'ada_banks_data_asset',

# Remove Date and Datetime column level

In [2]:
import chromadb
from chromadb.config import Settings

chromadb_setting = Settings(
    chroma_client_auth_provider="chromadb.auth.basic_authn.BasicAuthClientProvider",
    chroma_client_auth_credentials="userdata:userdataChromaPassw0rd",
)

client = chromadb.HttpClient(
    host="52.187.106.203",
    port=8000,
    settings=chromadb_setting,
)

# Specify your collection
collection_name = (
    "devtest4.ADA.banking.columnLevel"  # Replace with your collection name
)
collection = client.get_collection(collection_name)

# Query to find vectors with 'sql_data_type' in ['date', 'datetime']
metadata_to_remove = {"sql_data_type": ["date", "datetime"]}

# Retrieve all vectors from the collection
all_vectors = collection.get(
    where={"sql_data_type": {"$in": metadata_to_remove["sql_data_type"]}}
)

# Remove each vector that meets the criteria
for vector in all_vectors["ids"]:
    collection.delete(ids=[vector])

print("Vectors with sql_data_type 'date' or 'datetime' have been removed.")

Vectors with sql_data_type 'date' or 'datetime' have been removed.

In [ ]:
import chromadb
from chromadb.config import Settings

chromadb_setting = Settings(
    chroma_client_auth_provider="chromadb.auth.basic_authn.BasicAuthClientProvider",
    chroma_client_auth_credentials="userdata:userdataChromaPassw0rd",
)

client = chromadb.HttpClient(
    host="52.187.106.203",
    port=8000,
    settings=chromadb_setting,
)

devtest3_table = [""]

# Specify your collection
collection_name = (
    "devtest3.ADA.banking.columnLevel"  # Replace with your collection name
)
collection = client.get_collection(collection_name)

# Query to find vectors with 'sql_data_type' in ['date', 'datetime']
metadata_to_remove = {"sql_data_type": ["date", "datetime"]}

# Retrieve all vectors from the collection
all_vectors = collection.get(
    where={"sql_data_type": {"$in": metadata_to_remove["sql_data_type"]}}
)

# Remove each vector that meets the criteria
for vector in all_vectors["ids"]:
    collection.delete(ids=[vector])

print("Vectors with sql_data_type 'date' or 'datetime' have been removed.")

# Update Column Level Metadata

In [ ]:
import chromadb
from chromadb.config import Settings

chromadb_setting = Settings(
    chroma_client_auth_provider="chromadb.auth.basic_authn.BasicAuthClientProvider",
    chroma_client_auth_credentials="userdata:userdataChromaPassw0rd",
)

client = chromadb.HttpClient(
    host="52.187.106.203",
    port=8000,
    settings=chromadb_setting,
)

# Create or retrieve a collection
collection = client.get_or_create_collection("liberty.ADA.banking.columnLevel")

ids_edit_list = ["id422-MySQL-ada_banks_data_asset.rfm_projection_new.rfm_month"]


# Function to update metadata
def update_metadata(collection, record_id, new_metadata):
    # Retrieve the existing embedding for the record
    record = collection.get(
        ids=[record_id], include=["embeddings", "metadatas", "documents"]
    )
    embedding = record["embeddings"][0]

    # Delete the old record
    collection.delete(ids=[record_id])

    # Add the embedding back with the new metadata
    collection.add(embeddings=[embedding], ids=[record_id], metadatas=[new_metadata])


# Update metadata for a specific record (e.g., "id1")

result_collection = collection.get(
    ids=ids_edit_list, include=["embeddings", "metadatas", "documents"]
)

for id, embedding, metadata in zip(
    result_collection["ids"],
    result_collection["embeddings"],
    result_collection["metadatas"],
):
    new_metadata = metadata.copy()
    new_metadata["10_samples"] = (
        new_metadata["10_samples"].replace("2018", "2023").replace("2019", "2024")
    )
    new_metadata["all_samples"] = (
        new_metadata["all_samples"].replace("2018", "2023").replace("2019", "2024")
    )
    # new_metadata["avg_value"] = 2023
    new_metadata["max_value"] = (
        new_metadata["max_value"].replace("2018", "2023").replace("2019", "2024")
    )
    new_metadata["min_value"] = (
        new_metadata["min_value"].replace("2018", "2023").replace("2019", "2024")
    )
    new_metadata["universal_all_samples"] = new_metadata["all_samples"].replace(
        "2018", "2023"
    )
    # display(new_metadata)
    update_metadata(collection, id, new_metadata)

# # Verify the metadata update by fetching the updated record
# updated_record = collection.get(ids=["id1"])
# print("Updated metadata:", updated_record['metadatas'])